import = [ "~/.config/alacritty/themes/themes/dracula.toml" ]

live_config_reload = true

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 20
y = 20
